### ISSUE TITLE
Function to changeText

### ISSUE THREAD

**Issue by buckyj** [GreenInfo-Network/Leaflet-Control-Credits#1]
Hi, can you help me on how to write a function to change text.

**Comment by gregallensworth** [comment]
What specific part are you missing which needs my help? Or are you just
asking me to create this new feature?

**Comment by buckyj** [comment]
Yes if you can add a function to changeText I would be very grateful. Thank  you.

**Comment by gregallensworth** [comment]
OK, to rephrase the request: "please add a function to change text"
The phrasing you previously used, implies that you were attempting to write this function and required some assistance with it.

**Comment by buckyj** [comment]
Yes this is right.
Dne 4. jan. 2016 21:40 je oseba "Greg Allensworth" notifications@github.com
napisala:

**Comment by gregallensworth** [comment]
Done in commit 0fc70e9
See release 1.2
